TECHNICAL_ROLE_MARKERS = (
    "ai ",
    "android",
    "applied scientist",
    "architect",
    "backend",
    "cloud architect",
    "data analysis",
    "data analyst",
    "data architect",
    "data engineer",
    "data science",
    "data scientist",
    "database",
    "dba",
    "developer",
    "development",
    "devops",
    "engineer",
    "engineering",
    "frontend",
    "infrastructure",
    "ios",
    "machine learning",
    "member of technical staff",
    "mlops",
    "platform",
    "programmer",
    "qa",
    "research scientist",
    "rpa",
    "security",
    "server",
    "site reliability",
    "software",
    "solution architect",
    "개발",
    "개발자",
    "데이터 분석",
    "데이터과학",
    "데이터 사이언",
    "데이터 엔지니어",
    "데이터엔지니어",
    "데이터베이스",
    "보안",
    "모의해킹",
    "소프트웨어",
    "프로그래머",
    "엔지니어",
    "인프라",
    "서버 개발",
    "시스템 개발",
    "취약점",
    "앱 개발",
    "웹 개발",
    "s/w",
)

NON_TECHNICAL_ROLE_MARKERS = (
    "account executive",
    "artist",
    "business development",
    "business developer",
    "civil engineer",
    "counsel",
    "customer service",
    "clinical research",
    "coordinator",
    "facilities",
    "facility",
    "hvac",
    "icqa",
    "lawyer",
    "legal",
    "loss prevention",
    "marketing",
    "medical device qa",
    "mechanical engineer",
    "product manager",
    "product owner",
    "program manager",
    "project manager",
    " pm",
    "sales",
    "business strategy",
    "strategy developer",
    "tech bd",
    "냉난방",
    "노무",
    "마케팅",
    "변호사",
    "사업법",
    "사업개발",
    "상담 품질",
    "세일즈",
    "시설",
    "영업",
    "경영전략",
    "기획",
    "운영 개선",
    "공조",
    "과제책임자",
    "프로젝트 매니저",
    "의료기기 qa",
    "임상연구",
)

KOREA_LOCATION_MARKERS = (
    "gyeonggi",
    "korea",
    "pangyo",
    "seoul",
    "대한민국",
    "서울",
    "성남",
    "판교",
)


def is_technical_role(*values: str | None) -> bool:
    searchable = " ".join(value for value in values if value).casefold()
    if any(marker in searchable for marker in NON_TECHNICAL_ROLE_MARKERS):
        return False
    return any(marker in searchable for marker in TECHNICAL_ROLE_MARKERS)


def is_korea_technical_role(
    title: str | None,
    location: str | None,
) -> bool:
    normalized_location = (location or "").casefold()
    normalized_title = (title or "").strip().casefold()
    has_domestic_marker = any(
        marker in normalized_location for marker in KOREA_LOCATION_MARKERS
    ) or normalized_title.startswith(("[kr]", "(kr)", "kr "))
    return has_domestic_marker and is_technical_role(title)
