/* Generated by scripts/sync-technology-icons.mjs. */
export const GENERATED_TECHNOLOGY_BRAND_ASSETS = {
  "android": {
    "key": "android",
    "src": "/technology-logos/simple-icons/android.svg"
  },
  "ansible": {
    "key": "ansible",
    "src": "/technology-logos/simple-icons/ansible.svg"
  },
  "apacheairflow": {
    "key": "apacheairflow",
    "src": "/technology-logos/simple-icons/apacheairflow.svg"
  },
  "apachecassandra": {
    "key": "apachecassandra",
    "src": "/technology-logos/simple-icons/apachecassandra.svg"
  },
  "apacheflink": {
    "key": "apacheflink",
    "src": "/technology-logos/simple-icons/apacheflink.svg"
  },
  "apachehive": {
    "key": "apachehive",
    "src": "/technology-logos/simple-icons/apachehive.svg"
  },
  "apachekafka": {
    "key": "apachekafka",
    "src": "/technology-logos/simple-icons/apachekafka.svg"
  },
  "apachespark": {
    "key": "apachespark",
    "src": "/technology-logos/simple-icons/apachespark.svg"
  },
  "apple": {
    "key": "apple",
    "src": "/technology-logos/simple-icons/apple.svg"
  },
  "argo": {
    "key": "argo",
    "src": "/technology-logos/simple-icons/argo.svg"
  },
  "c": {
    "key": "c",
    "src": "/technology-logos/simple-icons/c.svg"
  },
  "celery": {
    "key": "celery",
    "src": "/technology-logos/simple-icons/celery.svg"
  },
  "clickhouse": {
    "key": "clickhouse",
    "src": "/technology-logos/simple-icons/clickhouse.svg"
  },
  "cmake": {
    "key": "cmake",
    "src": "/technology-logos/simple-icons/cmake.svg"
  },
  "cplusplus": {
    "key": "cplusplus",
    "src": "/technology-logos/simple-icons/cplusplus.svg"
  },
  "databricks": {
    "key": "databricks",
    "src": "/technology-logos/simple-icons/databricks.svg"
  },
  "datadog": {
    "key": "datadog",
    "src": "/technology-logos/simple-icons/datadog.svg"
  },
  "docker": {
    "key": "docker",
    "src": "/technology-logos/simple-icons/docker.svg"
  },
  "dotnet": {
    "key": "dotnet",
    "src": "/technology-logos/simple-icons/dotnet.svg"
  },
  "figma": {
    "key": "figma",
    "src": "/technology-logos/simple-icons/figma.svg"
  },
  "githubactions": {
    "key": "githubactions",
    "src": "/technology-logos/simple-icons/githubactions.svg"
  },
  "gitlab": {
    "key": "gitlab",
    "src": "/technology-logos/simple-icons/gitlab.svg"
  },
  "gnubash": {
    "key": "gnubash",
    "src": "/technology-logos/simple-icons/gnubash.svg"
  },
  "go": {
    "key": "go",
    "src": "/technology-logos/simple-icons/go.svg"
  },
  "googlebigquery": {
    "key": "googlebigquery",
    "src": "/technology-logos/simple-icons/googlebigquery.svg"
  },
  "googlecloud": {
    "key": "googlecloud",
    "src": "/technology-logos/simple-icons/googlecloud.svg"
  },
  "gradle": {
    "key": "gradle",
    "src": "/technology-logos/simple-icons/gradle.svg"
  },
  "grafana": {
    "key": "grafana",
    "src": "/technology-logos/simple-icons/grafana.svg"
  },
  "graphql": {
    "key": "graphql",
    "src": "/technology-logos/simple-icons/graphql.svg"
  },
  "helm": {
    "key": "helm",
    "src": "/technology-logos/simple-icons/helm.svg"
  },
  "huggingface": {
    "key": "huggingface",
    "src": "/technology-logos/simple-icons/huggingface.svg"
  },
  "istio": {
    "key": "istio",
    "src": "/technology-logos/simple-icons/istio.svg"
  },
  "jenkins": {
    "key": "jenkins",
    "src": "/technology-logos/simple-icons/jenkins.svg"
  },
  "jira": {
    "key": "jira",
    "src": "/technology-logos/simple-icons/jira.svg"
  },
  "junit5": {
    "key": "junit5",
    "src": "/technology-logos/simple-icons/junit5.svg"
  },
  "kotlin": {
    "key": "kotlin",
    "src": "/technology-logos/simple-icons/kotlin.svg"
  },
  "kubernetes": {
    "key": "kubernetes",
    "src": "/technology-logos/simple-icons/kubernetes.svg"
  },
  "linux": {
    "key": "linux",
    "src": "/technology-logos/simple-icons/linux.svg"
  },
  "mariadb": {
    "key": "mariadb",
    "src": "/technology-logos/simple-icons/mariadb.svg"
  },
  "milvus": {
    "key": "milvus",
    "src": "/technology-logos/simple-icons/milvus.svg"
  },
  "mlflow": {
    "key": "mlflow",
    "src": "/technology-logos/simple-icons/mlflow.svg"
  },
  "mongodb": {
    "key": "mongodb",
    "src": "/technology-logos/simple-icons/mongodb.svg"
  },
  "mqtt": {
    "key": "mqtt",
    "src": "/technology-logos/simple-icons/mqtt.svg"
  },
  "mysql": {
    "key": "mysql",
    "src": "/technology-logos/simple-icons/mysql.svg"
  },
  "nodedotjs": {
    "key": "nodedotjs",
    "src": "/technology-logos/simple-icons/nodedotjs.svg"
  },
  "numpy": {
    "key": "numpy",
    "src": "/technology-logos/simple-icons/numpy.svg"
  },
  "nvidia": {
    "key": "nvidia",
    "src": "/technology-logos/simple-icons/nvidia.svg"
  },
  "onnx": {
    "key": "onnx",
    "src": "/technology-logos/simple-icons/onnx.svg"
  },
  "openjdk": {
    "key": "openjdk",
    "src": "/technology-logos/simple-icons/openjdk.svg"
  },
  "opensearch": {
    "key": "opensearch",
    "src": "/technology-logos/simple-icons/opensearch.svg"
  },
  "opentelemetry": {
    "key": "opentelemetry",
    "src": "/technology-logos/simple-icons/opentelemetry.svg"
  },
  "pandas": {
    "key": "pandas",
    "src": "/technology-logos/simple-icons/pandas.svg"
  },
  "postgresql": {
    "key": "postgresql",
    "src": "/technology-logos/simple-icons/postgresql.svg"
  },
  "prometheus": {
    "key": "prometheus",
    "src": "/technology-logos/simple-icons/prometheus.svg"
  },
  "pytest": {
    "key": "pytest",
    "src": "/technology-logos/simple-icons/pytest.svg"
  },
  "python": {
    "key": "python",
    "src": "/technology-logos/simple-icons/python.svg"
  },
  "pytorch": {
    "key": "pytorch",
    "src": "/technology-logos/simple-icons/pytorch.svg"
  },
  "rabbitmq": {
    "key": "rabbitmq",
    "src": "/technology-logos/simple-icons/rabbitmq.svg"
  },
  "react": {
    "key": "react",
    "src": "/technology-logos/simple-icons/react.svg"
  },
  "reactquery": {
    "key": "reactquery",
    "src": "/technology-logos/simple-icons/reactquery.svg"
  },
  "redis": {
    "key": "redis",
    "src": "/technology-logos/simple-icons/redis.svg"
  },
  "redux": {
    "key": "redux",
    "src": "/technology-logos/simple-icons/redux.svg"
  },
  "sentry": {
    "key": "sentry",
    "src": "/technology-logos/simple-icons/sentry.svg"
  },
  "snowflake": {
    "key": "snowflake",
    "src": "/technology-logos/simple-icons/snowflake.svg"
  },
  "sonarqubeserver": {
    "key": "sonarqubeserver",
    "src": "/technology-logos/simple-icons/sonarqubeserver.svg"
  },
  "spring": {
    "key": "spring",
    "src": "/technology-logos/simple-icons/spring.svg"
  },
  "storybook": {
    "key": "storybook",
    "src": "/technology-logos/simple-icons/storybook.svg"
  },
  "tailwindcss": {
    "key": "tailwindcss",
    "src": "/technology-logos/simple-icons/tailwindcss.svg"
  },
  "terraform": {
    "key": "terraform",
    "src": "/technology-logos/simple-icons/terraform.svg"
  },
  "typescript": {
    "key": "typescript",
    "src": "/technology-logos/simple-icons/typescript.svg"
  },
  "unity": {
    "key": "unity",
    "src": "/technology-logos/simple-icons/unity.svg"
  },
  "vite": {
    "key": "vite",
    "src": "/technology-logos/simple-icons/vite.svg"
  },
  "vllm": {
    "key": "vllm",
    "src": "/technology-logos/simple-icons/vllm.svg"
  },
  "vulkan": {
    "key": "vulkan",
    "src": "/technology-logos/simple-icons/vulkan.svg"
  },
  "webpack": {
    "key": "webpack",
    "src": "/technology-logos/simple-icons/webpack.svg"
  },
  "webrtc": {
    "key": "webrtc",
    "src": "/technology-logos/simple-icons/webrtc.svg"
  }
} as const;
export type GeneratedTechnologyBrandKey = keyof typeof GENERATED_TECHNOLOGY_BRAND_ASSETS;
