import type { GeneratedTechnologyBrandKey } from "./technology-icon-assets.generated";

export type TechnologyBrandAsset = {
  key: string;
  src: string;
};

const BRAND_ALIASES: Record<string, GeneratedTechnologyBrandKey> = {
  ".net": "dotnet",
  android: "android",
  ansible: "ansible",
  "apache airflow": "apacheairflow",
  "apache cassandra": "apachecassandra",
  "apache flink": "apacheflink",
  "apache hive": "apachehive",
  "apache spark": "apachespark",
  "argo cd": "argo",
  bash: "gnubash",
  bigquery: "googlebigquery",
  c: "c",
  cassandra: "apachecassandra",
  celery: "celery",
  "c++": "cplusplus",
  clickhouse: "clickhouse",
  cmake: "cmake",
  databricks: "databricks",
  datadog: "datadog",
  docker: "docker",
  figma: "figma",
  gcp: "googlecloud",
  go: "go",
  golang: "go",
  gradle: "gradle",
  grafana: "grafana",
  graphql: "graphql",
  "github actions": "githubactions",
  "gitlab ci": "gitlab",
  helm: "helm",
  "hugging face": "huggingface",
  ios: "apple",
  istio: "istio",
  "isaac sim": "nvidia",
  java: "openjdk",
  jenkins: "jenkins",
  jira: "jira",
  junit: "junit5",
  kafka: "apachekafka",
  kotlin: "kotlin",
  kubernetes: "kubernetes",
  linux: "linux",
  mariadb: "mariadb",
  milvus: "milvus",
  mlflow: "mlflow",
  mongodb: "mongodb",
  mqtt: "mqtt",
  mysql: "mysql",
  "node.js": "nodedotjs",
  nodejs: "nodedotjs",
  numpy: "numpy",
  onnx: "onnx",
  openjdk: "openjdk",
  opensearch: "opensearch",
  opentelemetry: "opentelemetry",
  pandas: "pandas",
  postgresql: "postgresql",
  prometheus: "prometheus",
  pytest: "pytest",
  python: "python",
  pytorch: "pytorch",
  rabbitmq: "rabbitmq",
  react: "react",
  "react native": "react",
  "tanstack query": "reactquery",
  redis: "redis",
  redux: "redux",
  sentry: "sentry",
  snowflake: "snowflake",
  sonarqube: "sonarqubeserver",
  spring: "spring",
  "spring boot": "spring",
  storybook: "storybook",
  "tailwind css": "tailwindcss",
  tensorrt: "nvidia",
  terraform: "terraform",
  triton: "nvidia",
  typescript: "typescript",
  unity: "unity",
  vite: "vite",
  vllm: "vllm",
  vulkan: "vulkan",
  webpack: "webpack",
  webrtc: "webrtc",
};

export function resolveTechnologyBrandAsset(
  name: string,
): TechnologyBrandAsset | null {
  const normalized = name.trim().toLocaleLowerCase("en-US");
  const key = BRAND_ALIASES[normalized];
  return key
    ? {
        key,
        src: `/technology-logos/simple-icons/${key}.svg`,
      }
    : null;
}
