import type {
  CommunityPostFeedItem,
  InterviewReviewFeedItem,
} from "./types";

export const MOCK_COMMUNITY_POSTS: CommunityPostFeedItem[] = [
  {
    id: "career-move-3y-backend",
    type: "community_post",
    category: "이직 고민",
    authorId: "server-garden",
    authorName: "서버정원",
    authorHeadline: "백엔드 개발자 · 3년차",
    authorTone: "violet",
    createdAt: "2026-07-13T09:10:00.000Z",
    createdLabel: "2시간 전",
    title: "3년차 백엔드 개발자, 지금 이직하는 게 맞을까요?",
    body: "지금 회사가 나쁘지는 않지만 비슷한 업무만 반복하고 있어 성장 속도가 느린 것 같습니다. 제안을 받은 팀은 기술적으로 매력적이지만 규모가 작아 고민이에요.",
    tags: ["백엔드", "3~5년차", "연봉", "커리어 고민"],
    href: "/posts/career-move-3y-backend",
    metrics: { reactions: 32, comments: 47, saves: 18 },
    source: "mock",
  },
  {
    id: "kubernetes-experience",
    type: "community_post",
    category: "커리어 질문",
    authorId: "code-walk",
    authorName: "코드산책",
    authorHeadline: "플랫폼 엔지니어 · 5년차",
    authorTone: "blue",
    createdAt: "2026-07-13T07:35:00.000Z",
    createdLabel: "4시간 전",
    title: "Kubernetes 실무 경험은 어디서부터 쌓는 게 좋을까요?",
    body: "개인 클러스터 운영과 회사의 실제 장애 대응 사이 간극이 크게 느껴집니다. 면접에서 설명할 수 있는 수준의 경험을 만들려면 어떤 문제부터 다뤄보는 게 좋을까요?",
    tags: ["Kubernetes", "인프라", "포트폴리오"],
    href: "/posts/kubernetes-experience",
    metrics: { reactions: 41, comments: 26, saves: 37 },
    source: "mock",
  },
  {
    id: "salary-negotiation-range",
    type: "community_post",
    category: "이직 고민",
    authorId: "data-bear",
    authorName: "데이터곰",
    authorHeadline: "데이터 엔지니어 · 4년차",
    authorTone: "green",
    createdAt: "2026-07-12T21:20:00.000Z",
    createdLabel: "어제",
    title: "연봉 협상 범위, 시장 데이터와 어떻게 맞춰보시나요?",
    body: "동일 연차라도 회사와 역할에 따라 편차가 커서 기준을 잡기 어렵네요. 공개된 공고 범위와 실제 제안 사이를 어떻게 비교하는지 궁금합니다.",
    tags: ["연봉 협상", "데이터", "이직 준비"],
    href: "/posts/salary-negotiation-range",
    metrics: { reactions: 58, comments: 34, saves: 29 },
    source: "mock",
  },
  {
    id: "startup-or-enterprise",
    type: "community_post",
    category: "업무 이야기",
    authorId: "beyond-product",
    authorName: "제품너머",
    authorHeadline: "프론트엔드 개발자 · 6년차",
    authorTone: "orange",
    createdAt: "2026-07-11T12:05:00.000Z",
    createdLabel: "2일 전",
    title: "스타트업과 대기업, 성장의 모양이 정말 다르네요",
    body: "한쪽은 넓게 결정하고 다른 한쪽은 깊게 협업하게 됐습니다. 다음 이직에서는 회사 규모보다 내가 맡을 문제의 경계를 먼저 보려고 합니다.",
    tags: ["스타트업", "대기업", "커리어 회고"],
    href: "/posts/startup-or-enterprise",
    metrics: { reactions: 73, comments: 19, saves: 22 },
    source: "mock",
  },
];

export const MOCK_INTERVIEW_REVIEWS: InterviewReviewFeedItem[] = [
  {
    id: "platform-backend-first-round",
    type: "interview_review",
    category: "면접 후기",
    authorId: "night-builder",
    authorName: "빌드하는밤",
    authorHeadline: "서버 개발자 · 4년차",
    authorTone: "green",
    createdAt: "2026-07-13T05:00:00.000Z",
    createdLabel: "6시간 전",
    companyType: "국내 플랫폼 기업",
    role: "백엔드 개발",
    stage: "1차 기술 면접",
    title: "플랫폼 기업 백엔드 1차 기술 면접 후기",
    summary: "코딩 문제보다 운영 중 겪은 장애를 어떻게 좁혀갔는지 설명하는 시간이 길었습니다. 정답보다 관찰과 판단 근거를 구체적으로 묻는 면접이었어요.",
    tags: ["백엔드", "기술 면접", "장애 대응"],
    href: "/posts/platform-backend-first-round",
    metrics: { reactions: 68, comments: 23, saves: 31 },
    source: "mock",
  },
  {
    id: "saas-data-interview",
    type: "interview_review",
    category: "면접 후기",
    authorId: "query-cup",
    authorName: "쿼리한잔",
    authorHeadline: "데이터 분석가 · 3년차",
    authorTone: "blue",
    createdAt: "2026-07-10T14:45:00.000Z",
    createdLabel: "3일 전",
    companyType: "B2B SaaS 기업",
    role: "데이터 분석",
    stage: "실무진 인터뷰",
    title: "지표 정의부터 다시 물었던 데이터 직무 면접",
    summary: "SQL 풀이 뒤에 같은 수치를 팀마다 다르게 해석할 때 어떤 기준을 세울지 토론했습니다. 업무 맥락을 먼저 확인하는 태도를 중요하게 보는 느낌이었습니다.",
    tags: ["데이터 분석", "SQL", "지표 설계"],
    href: "/posts/saas-data-interview",
    metrics: { reactions: 49, comments: 17, saves: 28 },
    source: "mock",
  },
];

export const MOCK_SOCIAL_ITEMS = [
  MOCK_COMMUNITY_POSTS[0],
  MOCK_INTERVIEW_REVIEWS[0],
  MOCK_COMMUNITY_POSTS[1],
  MOCK_COMMUNITY_POSTS[2],
  MOCK_INTERVIEW_REVIEWS[1],
  MOCK_COMMUNITY_POSTS[3],
];
